KanzoBus.Web/Controllers/BusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using KanzoBus.Model;
using KanzoBus.Service;
using KanzoBus.Web.ViewModels;

namespace KanzoBus.Web.Controllers
{
    public class BusController : Controller
    {
        private readonly IBusService busService;

        public BusController(IBusService busService)
        {
            this.busService = busService;
        }

        // GET: Bus
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(BusViewModel viewModel)
        {
            if (viewModel != null)
            {
                var bus = Mapper.Map<BusViewModel,Bus>(viewModel);
                busService.CreateBus(bus);
                busService.Save();
                return RedirectToAction("Index", "Home");
            }
            return Content("Error");
        }
    }
}

KanzoBus.Web/Controllers/DriverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using KanzoBus.Model;
using KanzoBus.Service;
using KanzoBus.Web.ViewModels;

namespace KanzoBus.Web.Controllers
{
    public class DriverController : Controller
    {
        private readonly IDriverService driverService;

        public DriverController(IDriverService driverService)
        {
            this.driverService = driverService;
        }

        // GET: Driver
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult GetDrivers()
        {
            var drivers = driverService.GetDrivers().ToList();
            return View(drivers);
        }

        [HttpPost]
        public ActionResult Create(DriverViewModel viewModel)
        {
            if (viewModel != null)
            {
                var driver = Mapper.Map<DriverViewModel, Driver>(viewModel);
                driverService.CreateDriver(driver);
                driverService.SaveDriver();
                return RedirectToAction("Index","Home");
            }
            return Content("Error");
        }
    }
}

KanzoBus.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
 <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Travel &mdash; 100% Free Fully Responsive HTML5 Template by FREEHTML5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Template by FREEHTML5.CO" />
    <meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
    <meta name="author" content="FREEHTML5.CO" />
    <!--
      //////////////////////////////////////////////////////

      FREE HTML5 TEMPLATE
      DESIGNED & DEVELOPED by FREEHTML5.CO

      Website: 		http://freehtml5.co/
      Email: 			info@freehtml5.co
      Twitter: 		http://twitter.com/fh5co
      Facebook: 		https://www.facebook.com/fh5co

      //////////////////////////////////////////////////////
       -->
    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="shortcut icon" href="favicon.ico">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>

    @*<!-- Animate.css -->
    <link rel="stylesheet" href="~/Content/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="~/Content/css/icomoon.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.css">
    <!-- Superfish -->
    <link rel="stylesheet" href="~/Content/css/superfish.css">
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/Content/css/magnific-popup.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="~/Content/css/bootstrap-datepicker.min.css">
    <!-- CS Select -->
    <link rel="stylesheet" href="~/Content/css/cs-select.css">
    <link rel="stylesheet" href="~/Content/css/cs-skin-border.css">

    <link rel="stylesheet" href="~/Content/css/style.css">

    <!-- Modernizr JS -->
    <script src="~/Content/js/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="~/Content/js/respond.min.js"></script>
    <![endif]-->*@
    
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/Content/css/magnific-popup.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="~/Content/css/bootstrap-datepicker.min.css">

    @Styles.Render("~/Content/Bundle/Css")
    @Scripts.Render("~/Content/Bundle/Js")

</head>
<body>
    <div id="fh5co-wrapper">
        <div id="fh5co-page">
            <header id="fh5co-header-section" class="sticky-banner">
                <div class="container">
                    <div class="nav-header">
                        <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle dark"><i></i></a>
                        <h1 id="fh5co-logo"><a href="~/Content/index.html"><i class="icon-airplane"></i>Travel</a></h1>
                        <!-- START #fh5co-menu-wrap -->
                        <nav id="fh5co-menu-wrap" role="navigation">
                            <ul class="sf-menu" id="fh5co-primary-menu">
                                <li class="active">@Html.ActionLink("Home","Index","Home",null,null)</li>
                                <li>
                                    <a href="~/Content/vacation.html" class="fh5co-sub-ddown">Vacations</a>
                                    <ul class="fh5co-sub-menu">
                                        <li><a href="#">Family</a></li>
                                        <li><a href="#">CSS3 &amp; HTML5</a></li>
                                        <li><a href="#">Angular JS</a></li>
                                        <li><a href="#">Node JS</a></li>
                                        <li><a href="#">Django &amp; Python</a></li>
                                    </ul>
                                </li>
                                <li><a href="~/Content/flight.html">Flights</a></li>
                                <li>@Html.ActionLink("Register","Create","Register",null,null)</li>
                                <li><a href="~/Content/car.html">Car</a></li>
                                <li><a href="~/Content/blog.html">Blog</a></li>
                                <li><a href="~/Content/contact.html">Contact</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </header>
            <!-- end:header-top -->

@RenderBody()
            <footer>
                <div id="footer">
                    <div class="container">
                        <div class="row row-bottom-padded-md">
                            <div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
                                <h3>About Travel</h3>
                                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                            </div>
                            <div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
                                <h3>Top Flights Routes</h3>
                                <ul>
                                    @Html.ActionLink("Create Driver","Create","Driver",new {},null)
                                    @Html.ActionLink("Create Bus","Create","Bus",new {},null)
                                    <li><a href="#">Bangkok flights</a></li>
                                    <li><a href="#">Tokyo Flight</a></li>
                                    <li><a href="#">New York Flights</a></li>
                                </ul>
                            </div>
                            <div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
                                <h3>Top Hotels</h3>
                                <ul>
                                    <li><a href="#">Boracay Hotel</a></li>
                                    <li><a href="#">Dubai Hotel</a></li>
                                    <li><a href="#">Singapore Hotel</a></li>
                                    <li><a href="#">Manila Hotel</a></li>
                                </ul>
                            </div>
                            <div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
                                <h3>Interest</h3>
                                <ul>
                                    <li><a href="#">Beaches</a></li>
                                    <li><a href="#">Family Travel</a></li>
                                    <li><a href="#">Budget Travel</a></li>
                                    <li><a href="#">Food &amp; Drink</a></li>
                                    <li><a href="#">Honeymoon and Romance</a></li>
                                </ul>
                            </div>
                            <div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
                                <h3>Best Places</h3>
                                <ul>
                                    <li><a href="#">Boracay Beach</a></li>
                                    <li><a href="#">Dubai</a></li>
                                    <li><a href="#">Singapore</a></li>
                                    <li><a href="#">Hongkong</a></li>
                                </ul>
                            </div>
                            <div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
                                <h3>Affordable</h3>
                                <ul>
                                    <li><a href="#">Food &amp; Drink</a></li>
                                    <li><a href="#">Fare Flights</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-md-offset-3 text-center">
                                <p class="fh5co-social-icons">
                                    <a href="#"><i class="icon-twitter2"></i></a>
                                    <a href="#"><i class="icon-facebook2"></i></a>
                                    <a href="#"><i class="icon-instagram"></i></a>
                                    <a href="#"><i class="icon-dribbble2"></i></a>
                                    <a href="#"><i class="icon-youtube"></i></a>
                                </p>
                                <p>Copyright 2016 Free Html5 <a href="#">Module</a>. All Rights Reserved. <br>Made with <i class="icon-heart3"></i> by <a href="http://freehtml5.co/" target="_blank">Freehtml5.co</a> / Demo Images: <a href="https://unsplash.com/" target="_blank">Unsplash</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>

        </div>
        <!-- END fh5co-page -->
    </div>
    <!-- END fh5co-wrapper -->
    <!-- jQuery -->

@*<script src="~/Content/js/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="~/Content/js/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="~/Content/js/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="~/Content/js/jquery.waypoints.min.js"></script>
    <script src="~/Content/js/sticky.js"></script>
    <!-- Stellar -->
    <script src="~/Content/js/jquery.stellar.min.js"></script>
    <!-- Superfish -->
    <script src="~/Content/js/hoverIntent.js"></script>
    <script src="~/Content/js/superfish.js"></script>
    <!-- Magnific Popup -->
    <script src="~/Content/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Content/js/magnific-popup-options.js"></script>
    <!-- Date Picker -->
    <script src="~/Content/js/bootstrap-datepicker.min.js"></script>
    <!-- CS Select -->
    <script src="~/Content/js/classie.js"></script>
    <script src="~/Content/js/selectFx.js"></script>

    <!-- Main JS -->
    <script src="~/Content/js/main.js"></script>*@
    
</body>
</html>